### PR TITLE
Fix USR1 and USR2 signal translations

### LINKED ISSUE #9: No translations for USR1 and USR2 signals
When adding the USR1 and USR 2 signals by adding the 1 and 2 files to the allowed-signals directory the buttons appear correctly in runit-man, however they say:

`translation missing: en.runit.services.table.signals.1`

My guess is the rails i18n system doesn't like the use of a number as a tag.

The other signals that are not a number translate just fine when added.

### PR DESCRIPTION
**Pull request by szechyjs**
Fixes #9

### CODE REVIEW

**Comment by numbata** [comment]
:+1:

**Comment by akzhan** [comment]
+1

**Comment by szechyjs** [comment]
Bump. It would be really nice if this would get merged and the gem updated so I don't have to maintain a fork.

**Comment by numbata** [comment]
@akzhan as author of https://rubygems.org/gems/runit-man do you have permissions to merge PR?

**Comment by akzhan** [comment]
Will transfer weekend

**Comment by szechyjs** [comment]
:+1:

**Comment by szechyjs** [comment]
Is this going to be released to rubygems?

**Comment by akzhan** [comment]
Moved at my home and released as 2.4.14.

**Comment by numbata** [comment]
@akzhan thx

**Pull request merged**
